name = "cf-todos"
pages_build_output_dir="dist"
compatibility_date = "2024-07-18"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "STORAGE"
id = "b1be6683835145bcb03803571a511ec5"
